name: test

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Test
        run: |
          npm i
          npm test